export const isSigned = (value?: boolean) => value;
export const token =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJzY290dGxvdm9zNTAzQGdtYWlsLmNvbSIsImlzQWN0aXZlIjp0cnVlLCJyb2xlIjp7ImlkIjoxLCJuYW1lIjoiQURNSU4iLCJkZXNjcmlwdGlvbiI6InRoZSBhZG1pbiB1c2VyIHJvbGUifSwiaWF0IjoxNjc2NjYyMDcxLCJleHAiOjE2NzY3NDg0NzF9.7SxHplMsrS2d7i5ie2jQywg7VrgoEe6UTRAoXm-Pyno';
